from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .material_sync import H3MaterialSync
from .board_input_sync import H3BoardInputSync
from .motion_con import (
    NODE_CLASS_MAPPINGS as MOTION_CON_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MOTION_CON_NODE_DISPLAY_NAME_MAPPINGS,
)
from .stable_multi_lora_loader import (
    NODE_CLASS_MAPPINGS as STABLE_MULTI_LORA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STABLE_MULTI_LORA_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS.update(STABLE_MULTI_LORA_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(STABLE_MULTI_LORA_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS["H3MaterialSync"] = H3MaterialSync
NODE_DISPLAY_NAME_MAPPINGS["H3MaterialSync"] = "H3 素材同步桥"
NODE_CLASS_MAPPINGS["H3BoardInputSync"] = H3BoardInputSync
NODE_DISPLAY_NAME_MAPPINGS["H3BoardInputSync"] = "H3 图片音频无线同步桥"
NODE_CLASS_MAPPINGS.update(MOTION_CON_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MOTION_CON_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
