import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
const code = await readFile(new URL("../web/timeline_sync_adapter.js", import.meta.url), "utf8");
const {mergeMedia, checkTarget} = await import(`data:text/javascript;base64,${Buffer.from(code).toString("base64")}`);
const state = {version:4, selection:{start:2,duration:5}, images:[], audios:[], videoClips:[], segmentConfig:{count:1,segments:[{images:[],audios:[]}]}};
const image = {kind:"image",slot:0,name:"角色",info:{filename:"a.png",width:32,height:32}};
const first = mergeMedia(state,[image],17);
assert.equal(first.added,1);
assert.equal(state.images.length,0);
assert.equal(mergeMedia(first.state,[image],17).added,0);
first.state.segmentConfig.segments[0].images.push(first.state.images[0].id);
const replaced = mergeMedia(first.state,[{...image,info:{...image.info,filename:"b.png"}}],17);
assert.equal(replaced.updated,1);
assert.equal(replaced.state.segmentConfig.segments[0].images[0],replaced.state.images[0].id);
assert.deepEqual(replaced.state.selection,state.selection);
assert.equal(mergeMedia(replaced.state,[],17).state.images.length,1);
const video = {kind:"video",slot:0,name:"片段",info:{filename:"v.mp4",duration:10,hasVideo:true,hasAudio:true}};
const withVideo = mergeMedia(state,[video],17).state;
Object.assign(withVideo.videoClips[0],{start:4,trimStart:2,duration:3,referenceMode:"edit"});
const updated = mergeMedia(withVideo,[{...video,info:{...video.info,filename:"v2.mp4"}}],17).state;
assert.equal(updated.videoClips[0].start,4);
assert.equal(updated.videoClips[0].trimStart,2);
assert.equal(updated.videoClips[0].referenceMode,"edit");
assert.throws(()=>mergeMedia(withVideo,[{...video,info:{...video.info,filename:"short.mp4",duration:4}}],17),/短于/);
assert.throws(()=>mergeMedia(state,Array.from({length:10},(_,slot)=>({...image,slot,info:{...image.info,filename:`${slot}.png`}})),17),/容量/);
assert.throws(()=>checkTarget({type:"MiniMaxH3TimelinePlanner",__m3td:{state:{version:5}}}),/不兼容/);
console.log("PASS: deduplication, replacement, segment references, deletion retention, clip edits, capacity, compatibility");
